# flake8: noqa
"""baseline control plane schema

Revision ID: 20260608_0001
Revises: 
Create Date: 2026-08-05 11:08:39.930199
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '20260608_0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('page', sa.String(length=255), nullable=True),
    sa.Column('required_role', sa.String(length=64), nullable=True),
    sa.Column('required_permission', sa.String(length=128), nullable=True),
    sa.Column('access_granted', sa.Boolean(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_access_log_email_timestamp', 'access_log', ['email', 'timestamp'], unique=False)
    op.create_table('artifacts',
    sa.Column('artifact_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('artifact_type', sa.String(length=64), nullable=False),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('owner_principal_id', sa.String(length=255), nullable=False),
    sa.Column('sharing_principal_id', sa.String(length=255), nullable=True),
    sa.Column('selector_hash', sa.String(length=128), nullable=False),
    sa.Column('selector_payload', sa.JSON(), nullable=False),
    sa.Column('pipeline_version', sa.String(length=64), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('parameter_hash', sa.String(length=128), nullable=False),
    sa.Column('parameter_payload', sa.JSON(), nullable=False),
    sa.Column('storage_uri', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_accessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('access_count', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('artifact_id'),
    sa.UniqueConstraint('artifact_type', 'scope', 'selector_hash', 'parameter_hash', 'pipeline_version', 'model_version', 'owner_principal_id', name='uq_artifact_identity')
    )
    op.create_index('ix_artifacts_scope_status', 'artifacts', ['scope', 'status'], unique=False)
    op.create_table('config_audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('config_key', sa.String(length=255), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('instance_id', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_config_audit_key_updated', 'config_audit_log', ['config_key', 'updated_at'], unique=False)
    op.create_index('ix_config_audit_updated', 'config_audit_log', ['updated_at'], unique=False)
    op.create_table('runtime_config',
    sa.Column('config_key', sa.String(length=255), nullable=False),
    sa.Column('config_value', sa.Text(), nullable=False),
    sa.Column('config_type', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('config_key')
    )
    op.create_index('ix_runtime_config_updated', 'runtime_config', ['updated_at'], unique=False)
    op.create_table('sessions',
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('access_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index('ix_sessions_expires', 'sessions', ['expires_at'], unique=False)
    op.create_index('ix_sessions_updated', 'sessions', ['updated_at'], unique=False)
    op.create_index('ix_sessions_user', 'sessions', ['user_id'], unique=False)
    op.create_table('user_queries',
    sa.Column('query_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('query_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('assistant_type', sa.String(length=64), nullable=True),
    sa.Column('message_content', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('query_id')
    )
    op.create_index('ix_queries_session', 'user_queries', ['session_id'], unique=False)
    op.create_index('ix_queries_user_time', 'user_queries', ['user_id', 'query_timestamp'], unique=False)
    op.create_table('user_roles',
    sa.Column('role_name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('role_name')
    )
    op.create_table('artifact_jobs',
    sa.Column('job_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('artifact_id', sa.Integer(), nullable=True),
    sa.Column('artifact_type', sa.String(length=64), nullable=False),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('requester_principal_id', sa.String(length=255), nullable=True),
    sa.Column('selector_hash', sa.String(length=128), nullable=False),
    sa.Column('selector_payload', sa.JSON(), nullable=False),
    sa.Column('parameter_hash', sa.String(length=128), nullable=False),
    sa.Column('parameter_payload', sa.JSON(), nullable=False),
    sa.Column('pipeline_version', sa.String(length=64), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('worker_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifacts.artifact_id'], ),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_index('ix_artifact_jobs_status_created', 'artifact_jobs', ['status', 'created_at'], unique=False)
    op.create_table('authorized_users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=True),
    sa.Column('added_by', sa.String(length=255), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_accessed', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['role'], ['user_roles.role_name'], ),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_index('ix_authorized_users_role_active', 'authorized_users', ['role', 'active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_authorized_users_role_active', table_name='authorized_users')
    op.drop_table('authorized_users')
    op.drop_index('ix_artifact_jobs_status_created', table_name='artifact_jobs')
    op.drop_table('artifact_jobs')
    op.drop_table('user_roles')
    op.drop_index('ix_queries_user_time', table_name='user_queries')
    op.drop_index('ix_queries_session', table_name='user_queries')
    op.drop_table('user_queries')
    op.drop_index('ix_sessions_user', table_name='sessions')
    op.drop_index('ix_sessions_updated', table_name='sessions')
    op.drop_index('ix_sessions_expires', table_name='sessions')
    op.drop_table('sessions')
    op.drop_index('ix_runtime_config_updated', table_name='runtime_config')
    op.drop_table('runtime_config')
    op.drop_index('ix_config_audit_updated', table_name='config_audit_log')
    op.drop_index('ix_config_audit_key_updated', table_name='config_audit_log')
    op.drop_table('config_audit_log')
    op.drop_index('ix_artifacts_scope_status', table_name='artifacts')
    op.drop_table('artifacts')
    op.drop_index('ix_access_log_email_timestamp', table_name='access_log')
    op.drop_table('access_log')
    # ### end Alembic commands ###
