[global]
check_size = false
check_language = false
desktop_mode = true
max_bytes_text = 20000000
max_bytes_polars = 150000000

[llm]
llm_parameters = { temperature = 0.7, top_p = 0.7, max_tokens = 500, frequency_penalty = 0, presence_penalty = 0 }
llm_model = "gpt-4o-mini"
quota = 10

[cache]
cache_mode = false
cache_location = "firestore"
