[theme]
primaryColor="#F63366"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#EBECF0"
textColor="#262730"
font="Source Sans Pro"

[server]
enableXsrfProtection = false
enableCORS = false

[runner]
enforceSerializableSessionState = true

[client]
showSidebarNavigation = false
toolbarMode = "minimal"
